server:
  port: 8102

spring:
  profiles:
    active: dev

app:
  weather:
    api:
      url: http://api.openweathermap.org/data/2.5
      key: dfec87074fc77e7a90d0d2e06a1a7d13

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    com.alissonpedrina: INFO
    com.alissonpedrina.dojo.config: INFO

---

spring:
  porfiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pedrina
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      connection-test-query: select 1
  activemq:
    broker-url: tcp://localhost:61616

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-container:5432/postgres
    username: postgres
    password: pedrina
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      connection-test-query: select 1
  activemq:
    broker-url: tcp://activemq-container:61616
