package com.alissonpedrina.java17.config;

public enum ConfigEnum {

    POSTGRESQL_SCRIPT {
        @Override
        public String toString() {
            return "DROP TABLE IF EXISTS weather; \n" +
                    "CREATE TABLE weather (\n" +
                    "    id SERIAL NOT NULL ,\n" +
                    "    date TIMESTAMP,\n" +
                    "    info JSON,\n" +
                    "    PRIMARY KEY (id)\n" +
                    ");";
        }
    },
    H2_SCRIPT {
        @Override
        public String toString() {
            return "CREATE TABLE weather (\n" +
                    "    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                    "    date TIMESTAMP\n" +
                    "    info VARCHAR NOT NULL\n" +
                    ");";
        }
    }

}
